F combined robot hw
shadow-robot/sr_ur_arm pull request #26
Opened 2016-09-13 17:12 UTC by dg-shadow

Do not merge until changes have been made to HandE and HandH code to work with new system!

2017-05-02 18:45 UTC, toliver requested changes

2017-05-02 18:45 UTC, toliver commented on sr_ur_robot_hw/config/left_ur_arm_controller.yaml
> +la_sr_ur_robot_hw:
This file should be renamed as `la_sr_ur_robot_hw` is not a controller.

2017-05-02 18:45 UTC, toliver commented on sr_ur_robot_hw/config/right_ur_arm_controller.yaml
> -ra_sr_ur_controller:
File should be renamed.

2017-05-02 18:45 UTC, toliver commented on sr_ur_bringup/launch/sr_ur_left.launch
> +  <node name="arm_controller_spawner" pkg="controller_manager" type="spawner" output="screen" args="la_sr_ur_robot_hw"/>
Delete this. `la_sr_ur_robot_hw` is not a controller now.

2017-05-02 18:45 UTC, toliver commented on sr_ur_bringup/launch/sr_ur_system.launch
> +  <rosparam command="load" file="$(find sr_ur_robot_hw)/config/right_ur_arm_controller.yaml"/>
These 2 files should be renamed.

2017-05-02 18:45 UTC, toliver commented on sr_ur_bringup/launch/sr_ur_right.launch
> +  <rosparam command="load" file="$(find sr_ur_robot_hw)/config/right_ur_arm_controller.yaml"/>
These files should be renamed.

2017-05-02 18:45 UTC, toliver commented on sr_ur_bringup/launch/sr_ur_left.launch
> +  <rosparam command="load" file="$(find sr_ur_robot_hw)/config/left_ur_arm_controller.yaml"/>
These file should be renamed.

2017-05-02 18:45 UTC, toliver commented on sr_ur_bringup/launch/sr_ur_right.launch
> +  <node name="arm_controller_spawner" pkg="controller_manager" type="spawner" output="screen" args="ra_sr_ur_robot_hw"/>
Delete this. `ra_sr_ur_robot_hw` is not a controller now.

2017-05-02 18:45 UTC, toliver commented on sr_ur_launch/README.md
> +# Starting the robots (simulated / real)
This file is basically describing how to use hand E and hand E + arm.
We should modify it to also contain instructions to launch UR arm alone.

2017-05-02 18:45 UTC, toliver commented on sr_ur_launch/config/configuration.yaml
> +ra_sr_ur_robot_hw:
This is duplicating the information in right_ur_arm_controller.yaml. Maybe that file should be removed?

2017-05-02 18:45 UTC, toliver commented on sr_ur_launch/launch/right_arm.launch
> +<launch>
This file looks like a replacement for:

sr_ur_bringup/launch/sr_ur_right.launch

Should that one be deleted?

And the left arm one as well?

sr_ur_bringup/launch/sr_ur_left.launch

2017-05-02 18:45 UTC, toliver commented on sr_ur_launch/scripts/teach_mode_node
> +        self.joints = ["ffj0", "ffj3", "ffj4",
We will have to adapt this to be compatible with hand H. We need to add this to our Jira backlog.

2017-05-02 18:45 UTC, toliver commented on sr_ur_robot_hw/CMakeLists.txt
> +            sr_ur_robot_hw
Fix indentation.

2017-05-04 15:09 UTC, dg-shadow commented on sr_ur_launch/launch/right_arm.launch
> +<launch>
There is no left_arm one... We could either move both from sr_ur_bringup or just leave them there...

TBH, nothing anywhere I can find even uses sr_ur_launch for anything... we could just delete the whole package I think.

2017-05-04 15:10 UTC, dg-shadow commented on sr_ur_robot_hw/CMakeLists.txt
> +            sr_ur_robot_hw
?? 
Indentation looks correct...

2017-05-04 15:22 UTC, toliver approved these changes

2017-05-04 15:44 UTC, merged